name: epay_flutter
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # main #
  cupertino_icons: ^1.0.3
  nb_utils: ^4.4.1
  google_fonts: ^2.1.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_vector_icons: ^1.0.0
  flutter_staggered_animations: 1.0.0
  flare_flutter: ^3.0.1
  webview_flutter: ^2.0.10
  image_picker: ^0.8.1+4
  cached_network_image: ^3.0.0
  video_player: ^2.1.10
  package_info: ^2.0.2

  # EPay #
  passcode_screen: ^2.0.0
  scratcher: ^2.1.0
  carousel_slider: ^4.0.0
  native_device_orientation: ^1.0.0
  share: ^2.0.4
  camera: ^0.8.1+4
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/gPay/

